const preset = (config) => config;

export const PRO_EDITING_PRESETS = [
  preset({ id: 'sports_highlight_pro', name: 'Sports Highlight Pro', recommendedUse: 'Melhores momentos esportivos com energia, replay leve e legendas de impacto.', toolsPreferred: ['ffmpeg', 'ffprobe', 'opencv', 'pyscenedetect', 'tesseract', 'remotion', 'natron'], toolsRequired: ['ffmpeg', 'ffprobe'], fallbacks: ['Sem OCR: score por movimento/audio.', 'Sem Natron/Remotion: overlays via FFmpeg drawtext/zoom.'], cutRules: { targetWindowSeconds: 20, maxClipSeconds: 45, minClipSeconds: 6, emphasizePeaks: true }, visualRules: { reframeMode: 'active_subject', overlayStyle: 'sports_hype', speedRamp: 'light', freezeFrame: true }, captionRules: { style: 'big_hook', source: 'speech_or_manual', emphasizeKeywords: true }, motionRules: { punchZoom: true, replay: true, tacticalPause: false }, colorRules: { preset: 'sports_hype_contrast' }, audioRules: { chain: 'sports_impact' }, renderEffects: ['punch_zoom', 'freeze_frame', 'speed_ramp_light'] }),
  preset({ id: 'sports_tactical_analysis', name: 'Sports Tactical Analysis', recommendedUse: 'Explicacoes taticas com setas, pausas e foco didatico.', toolsPreferred: ['opencv', 'tesseract', 'yolo', 'manim', 'remotion', 'natron'], toolsRequired: ['ffmpeg', 'ffprobe'], fallbacks: ['Sem Manim/Natron: SVG/HTML overlays.', 'Sem OCR: anotacoes manuais.'], cutRules: { targetWindowSeconds: 35, maxClipSeconds: 90, minClipSeconds: 8, emphasizePeaks: false }, visualRules: { reframeMode: 'center_safe', overlayStyle: 'tactical', speedRamp: 'off', freezeFrame: true }, captionRules: { style: 'minimal_professional', source: 'speech_or_manual', emphasizeKeywords: false }, motionRules: { punchZoom: false, replay: false, tacticalPause: true }, colorRules: { preset: 'documentary_neutral' }, audioRules: { chain: 'social_loud_clean' }, renderEffects: ['freeze_frame', 'arrows', 'circles'] }),
  preset({ id: 'viral_shorts_aggressive', name: 'Viral Shorts Aggressive', recommendedUse: 'Shorts verticais com hook rapido, cortes agressivos e caption forte.', toolsPreferred: ['whisper', 'auto_editor', 'ffmpeg', 'remotion', 'svgHtmlCss'], toolsRequired: ['ffmpeg', 'ffprobe'], fallbacks: ['Sem Whisper: captions manuais.', 'Sem auto-editor: cortes por heuristica local.'], cutRules: { targetWindowSeconds: 18, maxClipSeconds: 35, minClipSeconds: 5, emphasizePeaks: true }, visualRules: { reframeMode: 'face_aware', overlayStyle: 'viral', speedRamp: 'light', freezeFrame: false }, captionRules: { style: 'capcut_bold', source: 'whisper_or_manual', emphasizeKeywords: true }, motionRules: { punchZoom: true, replay: false, tacticalPause: false }, colorRules: { preset: 'viral_punchy_mobile' }, audioRules: { chain: 'social_loud_clean' }, renderEffects: ['fast_cuts', 'hook_title', 'caption_pop'] }),
  preset({ id: 'podcast_clean_cut', name: 'Podcast Clean Cut', recommendedUse: 'Cortes limpos de podcast com legendas elegantes e foco no rosto.', toolsPreferred: ['whisper', 'auto_editor', 'mediapipe', 'ffmpeg'], toolsRequired: ['ffmpeg', 'ffprobe'], fallbacks: ['Sem face tracking: crop central.', 'Sem Whisper: sem legenda automatica.'], cutRules: { targetWindowSeconds: 45, maxClipSeconds: 120, minClipSeconds: 12, emphasizePeaks: false }, visualRules: { reframeMode: 'face_aware', overlayStyle: 'podcast_clean', speedRamp: 'off', freezeFrame: false }, captionRules: { style: 'minimal_professional', source: 'whisper_or_manual', emphasizeKeywords: true }, motionRules: { punchZoom: false, replay: false, tacticalPause: false }, colorRules: { preset: 'podcast_clean_color' }, audioRules: { chain: 'podcast_voice_clean' }, renderEffects: ['speaker_reframe', 'clean_captions'] }),
  preset({ id: 'worship_music_clean', name: 'Worship / Music Clean', recommendedUse: 'Performance musical com cortes suaves e respeito a dinamica.', toolsPreferred: ['librosa', 'aubio', 'ffmpeg'], toolsRequired: ['ffmpeg', 'ffprobe'], fallbacks: ['Sem beat detection: cortes por janelas e transicoes suaves.'], cutRules: { targetWindowSeconds: 40, maxClipSeconds: 90, minClipSeconds: 10, emphasizePeaks: false }, visualRules: { reframeMode: 'center_safe', overlayStyle: 'worship', speedRamp: 'off', freezeFrame: false }, captionRules: { style: 'worship_clean', source: 'manual', emphasizeKeywords: false }, motionRules: { punchZoom: false, replay: false, tacticalPause: false }, colorRules: { preset: 'worship_soft_film' }, audioRules: { chain: 'worship_music_safe' }, renderEffects: ['soft_transitions', 'beat_alignment_light'] }),
  preset({ id: 'documentary_recap', name: 'Documentary Recap', recommendedUse: 'Resumo narrativo com lower thirds, ritmo mais lento e cara cinematografica.', toolsPreferred: ['whisper', 'pyscenedetect', 'blender', 'natron', 'lutCube'], toolsRequired: ['ffmpeg', 'ffprobe'], fallbacks: ['Sem Blender/Natron: lower thirds via SVG.', 'Sem LUT: filtros FFmpeg.'], cutRules: { targetWindowSeconds: 55, maxClipSeconds: 150, minClipSeconds: 12, emphasizePeaks: false }, visualRules: { reframeMode: 'center_safe', overlayStyle: 'documentary', speedRamp: 'off', freezeFrame: false }, captionRules: { style: 'clean', source: 'whisper_or_manual', emphasizeKeywords: false }, motionRules: { punchZoom: false, replay: false, tacticalPause: false }, colorRules: { preset: 'documentary_neutral' }, audioRules: { chain: 'social_loud_clean' }, renderEffects: ['lower_thirds', 'slow_reveals'] }),
  preset({ id: 'product_offer_clip', name: 'Product / Offer Clip', recommendedUse: 'Oferta, produto e CTA com overlays limpos e leitura imediata.', toolsPreferred: ['ffmpeg', 'svgHtmlCss', 'remotion', 'sharp'], toolsRequired: ['ffmpeg', 'ffprobe'], fallbacks: ['Sem Remotion: overlays com drawtext e PNG/SVG estaticos.'], cutRules: { targetWindowSeconds: 20, maxClipSeconds: 40, minClipSeconds: 5, emphasizePeaks: true }, visualRules: { reframeMode: 'center_safe', overlayStyle: 'product_premium', speedRamp: 'light', freezeFrame: false }, captionRules: { style: 'big_hook', source: 'speech_or_manual', emphasizeKeywords: true }, motionRules: { punchZoom: true, replay: false, tacticalPause: false }, colorRules: { preset: 'product_premium_look' }, audioRules: { chain: 'social_loud_clean' }, renderEffects: ['headline', 'cta', 'benefit_overlay'] }),
  preset({ id: 'tutorial_educational', name: 'Tutorial / Educational', recommendedUse: 'Aulas, walkthroughs e conteudo explicativo com labels e zoom em tela.', toolsPreferred: ['manim', 'svgHtmlCss', 'whisper', 'ffmpeg'], toolsRequired: ['ffmpeg', 'ffprobe'], fallbacks: ['Sem Manim: SVG/HTML annotations.', 'Sem Whisper: capitulos manuais.'], cutRules: { targetWindowSeconds: 35, maxClipSeconds: 90, minClipSeconds: 10, emphasizePeaks: false }, visualRules: { reframeMode: 'center_safe', overlayStyle: 'tutorial', speedRamp: 'off', freezeFrame: true }, captionRules: { style: 'clean', source: 'whisper_or_manual', emphasizeKeywords: true }, motionRules: { punchZoom: false, replay: false, tacticalPause: true }, colorRules: { preset: 'documentary_neutral' }, audioRules: { chain: 'podcast_voice_clean' }, renderEffects: ['labels', 'screen_zoom', 'chapters'] }),
  preset({ id: 'cinematic_sports_story', name: 'Cinematic Sports Story', recommendedUse: 'Storytelling esportivo com look contrastado e ritmo emocional.', toolsPreferred: ['pyscenedetect', 'opencv', 'lutCube', 'ffmpeg', 'remotion'], toolsRequired: ['ffmpeg', 'ffprobe'], fallbacks: ['Sem LUT: color FFmpeg.', 'Sem PySceneDetect: cortes por janelas e score local.'], cutRules: { targetWindowSeconds: 45, maxClipSeconds: 90, minClipSeconds: 8, emphasizePeaks: true }, visualRules: { reframeMode: 'active_subject', overlayStyle: 'cinematic_story', speedRamp: 'light', freezeFrame: true }, captionRules: { style: 'clean', source: 'speech_or_manual', emphasizeKeywords: true }, motionRules: { punchZoom: true, replay: true, tacticalPause: false }, colorRules: { preset: 'cinematic_high_contrast' }, audioRules: { chain: 'sports_impact' }, renderEffects: ['slow_motion_light', 'story_titles', 'contrast_grade'] }),
  preset({ id: 'social_proof_reaction', name: 'Social Proof / Reaction', recommendedUse: 'Reacoes, prova social e videos em dupla ou comparacao.', toolsPreferred: ['whisper', 'opencv', 'ffmpeg', 'svgHtmlCss'], toolsRequired: ['ffmpeg', 'ffprobe'], fallbacks: ['Sem Whisper: captions basicas.', 'Sem OpenCV: split estatico.'], cutRules: { targetWindowSeconds: 25, maxClipSeconds: 50, minClipSeconds: 6, emphasizePeaks: true }, visualRules: { reframeMode: 'face_aware', overlayStyle: 'reaction', speedRamp: 'light', freezeFrame: false }, captionRules: { style: 'tiktok_highlight', source: 'whisper_or_manual', emphasizeKeywords: true }, motionRules: { punchZoom: true, replay: false, tacticalPause: false }, colorRules: { preset: 'viral_punchy_mobile' }, audioRules: { chain: 'social_loud_clean' }, renderEffects: ['split_screen', 'reaction_caption', 'face_zoom'] }),
];

// ── Full Studio presets (requerem toolchain profissional completo) ─────────
export const FULL_STUDIO_PRESETS = [
  preset({ id: 'sports_broadcast_full_studio', name: 'Sports Broadcast Full Studio', recommendedUse: 'Transmissão esportiva nível broadcast com YOLO tracking, color grade HDR, áudio SCR e composição Blender.', toolsRequired: ['ffmpeg', 'ffprobe', 'opencv', 'pyscenedetect', 'yolo', 'librosa', 'imagemagick', 'sox'], requiresBlender: true, requiresNatron: false, engineProfile: 'full_studio', cutRules: { targetWindowSeconds: 30, maxClipSeconds: 60, minClipSeconds: 5, emphasizePeaks: true }, visualRules: { reframeMode: 'active_subject', overlayStyle: 'sports_hype', speedRamp: 'light', freezeFrame: true }, captionRules: { style: 'big_hook', source: 'speech_or_manual', emphasizeKeywords: true }, motionRules: { punchZoom: true, replay: true, tacticalPause: false }, colorRules: { preset: 'sports_hype_contrast' }, audioRules: { chain: 'sports_impact' }, renderEffects: ['punch_zoom', 'freeze_frame', 'hdr_grade', 'yolo_track'] }),
  preset({ id: 'cinematic_trailer_full_studio', name: 'Cinematic Trailer Full Studio', recommendedUse: 'Trailer cinemático nível After Effects com Blender motion blur, LUT cube e composição multi-camada.', toolsRequired: ['ffmpeg', 'ffprobe', 'imagemagick'], requiresBlender: true, requiresNatron: false, engineProfile: 'full_studio', cutRules: { targetWindowSeconds: 20, maxClipSeconds: 90, minClipSeconds: 3, emphasizePeaks: true }, visualRules: { reframeMode: 'center_safe', overlayStyle: 'cinematic_story', speedRamp: 'light', freezeFrame: true }, captionRules: { style: 'clean', source: 'manual', emphasizeKeywords: false }, motionRules: { punchZoom: true, replay: false, tacticalPause: false }, colorRules: { preset: 'cinematic_high_contrast' }, audioRules: { chain: 'sports_impact' }, renderEffects: ['motion_blur_blender', 'lut_cube', 'multi_layer'] }),
  preset({ id: 'worship_atmosphere_full_studio', name: 'Worship Atmosphere Full Studio', recommendedUse: 'Louvor cinematográfico com CamillaDSP, Natron color e librosa beat-sync.', toolsRequired: ['ffmpeg', 'ffprobe', 'librosa', 'camilladsp', 'sox'], requiresBlender: true, requiresNatron: true, engineProfile: 'full_studio', cutRules: { targetWindowSeconds: 45, maxClipSeconds: 180, minClipSeconds: 12, emphasizePeaks: false }, visualRules: { reframeMode: 'center_safe', overlayStyle: 'worship', speedRamp: 'off', freezeFrame: false }, captionRules: { style: 'worship_clean', source: 'manual', emphasizeKeywords: false }, motionRules: { punchZoom: false, replay: false, tacticalPause: false }, colorRules: { preset: 'worship_soft_film' }, audioRules: { chain: 'worship_music_safe' }, renderEffects: ['natron_color', 'beat_sync', 'camilla_dsp'] }),
  preset({ id: 'podcast_studio_full_studio', name: 'Podcast Studio Full Studio', engineProfile: 'full_studio', recommendedUse: 'Podcast com face tracking OpenCV, limpeza de voz Sox/CamillaDSP, Whisper e captions elegantes.', toolsRequired: ['ffmpeg', 'ffprobe', 'whisper', 'opencv', 'sox'], requiresBlender: false, requiresNatron: false, cutRules: { targetWindowSeconds: 60, maxClipSeconds: 180, minClipSeconds: 15, emphasizePeaks: false }, visualRules: { reframeMode: 'face_aware', overlayStyle: 'podcast_clean', speedRamp: 'off', freezeFrame: false }, captionRules: { style: 'minimal_professional', source: 'whisper_or_manual', emphasizeKeywords: true }, motionRules: { punchZoom: false, replay: false, tacticalPause: false }, colorRules: { preset: 'podcast_clean_color' }, audioRules: { chain: 'podcast_voice_clean' }, renderEffects: ['face_track_opencv', 'whisper_captions', 'sox_voice_clean'] }),
  preset({ id: 'viral_kinetic_full_studio', name: 'Viral Kinetic Full Studio', engineProfile: 'full_studio', recommendedUse: 'Reels virais com Whisper auto-caption, ImageMagick overlays kinéticos e libvips blur/grade.', toolsRequired: ['ffmpeg', 'ffprobe', 'whisper', 'imagemagick', 'libvips', 'sox'], requiresBlender: false, requiresNatron: false, cutRules: { targetWindowSeconds: 15, maxClipSeconds: 30, minClipSeconds: 3, emphasizePeaks: true }, visualRules: { reframeMode: 'face_aware', overlayStyle: 'viral', speedRamp: 'light', freezeFrame: false }, captionRules: { style: 'capcut_bold', source: 'whisper_or_manual', emphasizeKeywords: true }, motionRules: { punchZoom: true, replay: false, tacticalPause: false }, colorRules: { preset: 'viral_punchy_mobile' }, audioRules: { chain: 'social_loud_clean' }, renderEffects: ['kinetic_overlays_imagemagick', 'libvips_grade', 'whisper_captions'] }),
  preset({ id: 'product_premium_full_studio', name: 'Product Premium Full Studio', engineProfile: 'full_studio', recommendedUse: 'Vídeo de produto premium com ImageMagick compositing, libvips e CTA overlays de alta qualidade.', toolsRequired: ['ffmpeg', 'ffprobe', 'imagemagick', 'libvips', 'sox'], requiresBlender: false, requiresNatron: false, cutRules: { targetWindowSeconds: 25, maxClipSeconds: 60, minClipSeconds: 5, emphasizePeaks: true }, visualRules: { reframeMode: 'center_safe', overlayStyle: 'product_premium', speedRamp: 'light', freezeFrame: false }, captionRules: { style: 'big_hook', source: 'speech_or_manual', emphasizeKeywords: true }, motionRules: { punchZoom: true, replay: false, tacticalPause: false }, colorRules: { preset: 'product_premium_look' }, audioRules: { chain: 'social_loud_clean' }, renderEffects: ['imagemagick_composite', 'libvips_premium', 'cta_overlay'] }),
];

export const ALL_PRESETS = [...PRO_EDITING_PRESETS, ...FULL_STUDIO_PRESETS];

export function listProEditingPresets() { return PRO_EDITING_PRESETS; }
export function listAllPresets() { return ALL_PRESETS; }
export function listFullStudioPresets() { return FULL_STUDIO_PRESETS; }
export function getProEditingPreset(id = '') {
  return ALL_PRESETS.find((item) => item.id === String(id || '').trim()) || PRO_EDITING_PRESETS[0];
}

export default { PRO_EDITING_PRESETS, FULL_STUDIO_PRESETS, ALL_PRESETS, listProEditingPresets, listAllPresets, listFullStudioPresets, getProEditingPreset };
